// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

import "github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"

type GrowtopiaWorld struct {
	Version uint16
	Unk1 uint32
	Name *GrowtopiaWorld_GtStr
	Width uint32
	Height uint32
	NumTiles uint32
	Unk2 []byte
	Tiles []*GrowtopiaWorld_WorldTile
	Unk3 []byte
	NumObjects uint32
	LastObjectUid uint32
	Objects []*GrowtopiaWorld_WorldObject
	_io *kaitai.Stream
	_root *GrowtopiaWorld
	_parent kaitai.Struct
}
func NewGrowtopiaWorld() *GrowtopiaWorld {
	return &GrowtopiaWorld{
	}
}

func (this GrowtopiaWorld) IO_() *kaitai.Stream {
	return this._io
}

func (this *GrowtopiaWorld) Read(io *kaitai.Stream, parent kaitai.Struct, root *GrowtopiaWorld) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.Version = uint16(tmp1)
	tmp2, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.Unk1 = uint32(tmp2)
	tmp3 := NewGrowtopiaWorld_GtStr()
	err = tmp3.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.Name = tmp3
	tmp4, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.Width = uint32(tmp4)
	tmp5, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.Height = uint32(tmp5)
	tmp6, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.NumTiles = uint32(tmp6)
	tmp7, err := this._io.ReadBytes(int(5))
	if err != nil {
		return err
	}
	tmp7 = tmp7
	this.Unk2 = tmp7
	for i := 0; i < int(this.NumTiles); i++ {
		_ = i
		tmp8 := NewGrowtopiaWorld_WorldTile()
		err = tmp8.Read(this._io, this, this._root)
		if err != nil {
			return err
		}
		this.Tiles = append(this.Tiles, tmp8)
	}
	tmp9, err := this._io.ReadBytes(int(12))
	if err != nil {
		return err
	}
	tmp9 = tmp9
	this.Unk3 = tmp9
	tmp10, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.NumObjects = uint32(tmp10)
	tmp11, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.LastObjectUid = uint32(tmp11)
	for i := 0; i < int(this.NumObjects); i++ {
		_ = i
		tmp12 := NewGrowtopiaWorld_WorldObject()
		err = tmp12.Read(this._io, this, this._root)
		if err != nil {
			return err
		}
		this.Objects = append(this.Objects, tmp12)
	}
	return err
}
type GrowtopiaWorld_ARGB struct {
	A uint8
	R uint8
	G uint8
	B uint8
	_io *kaitai.Stream
	_root *GrowtopiaWorld
	_parent *GrowtopiaWorld_SilkWormExtra
}
func NewGrowtopiaWorld_ARGB() *GrowtopiaWorld_ARGB {
	return &GrowtopiaWorld_ARGB{
	}
}

func (this GrowtopiaWorld_ARGB) IO_() *kaitai.Stream {
	return this._io
}

func (this *GrowtopiaWorld_ARGB) Read(io *kaitai.Stream, parent *GrowtopiaWorld_SilkWormExtra, root *GrowtopiaWorld) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp13, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.A = tmp13
	tmp14, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.R = tmp14
	tmp15, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.G = tmp15
	tmp16, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.B = tmp16
	return err
}
type GrowtopiaWorld_AchievementBlockExtra struct {
	Unk1 uint32
	AchievementId uint8
	_io *kaitai.Stream
	_root *GrowtopiaWorld
	_parent *GrowtopiaWorld_WorldTile
}
func NewGrowtopiaWorld_AchievementBlockExtra() *GrowtopiaWorld_AchievementBlockExtra {
	return &GrowtopiaWorld_AchievementBlockExtra{
	}
}

func (this GrowtopiaWorld_AchievementBlockExtra) IO_() *kaitai.Stream {
	return this._io
}

func (this *GrowtopiaWorld_AchievementBlockExtra) Read(io *kaitai.Stream, parent *GrowtopiaWorld_WorldTile, root *GrowtopiaWorld) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp17, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.Unk1 = uint32(tmp17)
	tmp18, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.AchievementId = tmp18
	return err
}
type GrowtopiaWorld_AdventureBeginsExtra struct {
	_io *kaitai.Stream
	_root *GrowtopiaWorld
	_parent *GrowtopiaWorld_WorldTile
}
func NewGrowtopiaWorld_AdventureBeginsExtra() *GrowtopiaWorld_AdventureBeginsExtra {
	return &GrowtopiaWorld_AdventureBeginsExtra{
	}
}

func (this GrowtopiaWorld_AdventureBeginsExtra) IO_() *kaitai.Stream {
	return this._io
}

func (this *GrowtopiaWorld_AdventureBeginsExtra) Read(io *kaitai.Stream, parent *GrowtopiaWorld_WorldTile, root *GrowtopiaWorld) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	return err
}

type GrowtopiaWorld_AngelicCountingCloudExtra_States int
const (
	GrowtopiaWorld_AngelicCountingCloudExtra_States__Raffling GrowtopiaWorld_AngelicCountingCloudExtra_States = 1
	GrowtopiaWorld_AngelicCountingCloudExtra_States__DoneRaffling GrowtopiaWorld_AngelicCountingCloudExtra_States = 2
)
var values_GrowtopiaWorld_AngelicCountingCloudExtra_States = map[GrowtopiaWorld_AngelicCountingCloudExtra_States]struct{}{1: {}, 2: {}}
func (v GrowtopiaWorld_AngelicCountingCloudExtra_States) isDefined() bool {
	_, ok := values_GrowtopiaWorld_AngelicCountingCloudExtra_States[v]
	return ok
}
type GrowtopiaWorld_AngelicCountingCloudExtra struct {
	State GrowtopiaWorld_AngelicCountingCloudExtra_States
	Unk1 uint16
	AsciiCode uint8
	_io *kaitai.Stream
	_root *GrowtopiaWorld
	_parent *GrowtopiaWorld_WorldTile
}
func NewGrowtopiaWorld_AngelicCountingCloudExtra() *GrowtopiaWorld_AngelicCountingCloudExtra {
	return &GrowtopiaWorld_AngelicCountingCloudExtra{
	}
}

func (this GrowtopiaWorld_AngelicCountingCloudExtra) IO_() *kaitai.Stream {
	return this._io
}

func (this *GrowtopiaWorld_AngelicCountingCloudExtra) Read(io *kaitai.Stream, parent *GrowtopiaWorld_WorldTile, root *GrowtopiaWorld) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp19, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.State = GrowtopiaWorld_AngelicCountingCloudExtra_States(tmp19)
	tmp20, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.Unk1 = uint16(tmp20)
	if (this.State == GrowtopiaWorld_AngelicCountingCloudExtra_States__DoneRaffling) {
		tmp21, err := this._io.ReadU1()
		if err != nil {
			return err
		}
		this.AsciiCode = tmp21
	}
	return err
}
type GrowtopiaWorld_AudioRackExtra struct {
	Note *GrowtopiaWorld_GtStr
	Volume uint32
	_io *kaitai.Stream
	_root *GrowtopiaWorld
	_parent *GrowtopiaWorld_WorldTile
}
func NewGrowtopiaWorld_AudioRackExtra() *GrowtopiaWorld_AudioRackExtra {
	return &GrowtopiaWorld_AudioRackExtra{
	}
}

func (this GrowtopiaWorld_AudioRackExtra) IO_() *kaitai.Stream {
	return this._io
}

func (this *GrowtopiaWorld_AudioRackExtra) Read(io *kaitai.Stream, parent *GrowtopiaWorld_WorldTile, root *GrowtopiaWorld) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp22 := NewGrowtopiaWorld_GtStr()
	err = tmp22.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.Note = tmp22
	tmp23, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.Volume = uint32(tmp23)
	return err
}
type GrowtopiaWorld_BalloonOMaticExtra struct {
	TotalRarity uint32
	TeamType uint8
	_io *kaitai.Stream
	_root *GrowtopiaWorld
	_parent *GrowtopiaWorld_WorldTile
}
func NewGrowtopiaWorld_BalloonOMaticExtra() *GrowtopiaWorld_BalloonOMaticExtra {
	return &GrowtopiaWorld_BalloonOMaticExtra{
	}
}

func (this GrowtopiaWorld_BalloonOMaticExtra) IO_() *kaitai.Stream {
	return this._io
}

func (this *GrowtopiaWorld_BalloonOMaticExtra) Read(io *kaitai.Stream, parent *GrowtopiaWorld_WorldTile, root *GrowtopiaWorld) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp24, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.TotalRarity = uint32(tmp24)
	tmp25, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.TeamType = tmp25
	return err
}
type GrowtopiaWorld_CborData struct {
	LenData uint32
	Data []byte
	_io *kaitai.Stream
	_root *GrowtopiaWorld
	_parent *GrowtopiaWorld_WorldTile
}
func NewGrowtopiaWorld_CborData() *GrowtopiaWorld_CborData {
	return &GrowtopiaWorld_CborData{
	}
}

func (this GrowtopiaWorld_CborData) IO_() *kaitai.Stream {
	return this._io
}

func (this *GrowtopiaWorld_CborData) Read(io *kaitai.Stream, parent *GrowtopiaWorld_WorldTile, root *GrowtopiaWorld) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp26, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.LenData = uint32(tmp26)
	tmp27, err := this._io.ReadBytes(int(this.LenData))
	if err != nil {
		return err
	}
	tmp27 = tmp27
	this.Data = tmp27
	return err
}
type GrowtopiaWorld_ChallengeTimerExtra struct {
	_io *kaitai.Stream
	_root *GrowtopiaWorld
	_parent *GrowtopiaWorld_WorldTile
}
func NewGrowtopiaWorld_ChallengeTimerExtra() *GrowtopiaWorld_ChallengeTimerExtra {
	return &GrowtopiaWorld_ChallengeTimerExtra{
	}
}

func (this GrowtopiaWorld_ChallengeTimerExtra) IO_() *kaitai.Stream {
	return this._io
}

func (this *GrowtopiaWorld_ChallengeTimerExtra) Read(io *kaitai.Stream, parent *GrowtopiaWorld_WorldTile, root *GrowtopiaWorld) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	return err
}
type GrowtopiaWorld_ChemsynthTankExtra struct {
	CurrentChemId uint32
	SupposedChemId uint32
	_io *kaitai.Stream
	_root *GrowtopiaWorld
	_parent *GrowtopiaWorld_WorldTile
}
func NewGrowtopiaWorld_ChemsynthTankExtra() *GrowtopiaWorld_ChemsynthTankExtra {
	return &GrowtopiaWorld_ChemsynthTankExtra{
	}
}

func (this GrowtopiaWorld_ChemsynthTankExtra) IO_() *kaitai.Stream {
	return this._io
}

func (this *GrowtopiaWorld_ChemsynthTankExtra) Read(io *kaitai.Stream, parent *GrowtopiaWorld_WorldTile, root *GrowtopiaWorld) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp28, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.CurrentChemId = uint32(tmp28)
	tmp29, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.SupposedChemId = uint32(tmp29)
	return err
}
type GrowtopiaWorld_ContainmentFieldPowerNodeExtra struct {
	TimeMs uint32
	NumLinkedNodes uint32
	LinkedNodes []uint32
	_io *kaitai.Stream
	_root *GrowtopiaWorld
	_parent *GrowtopiaWorld_WorldTile
}
func NewGrowtopiaWorld_ContainmentFieldPowerNodeExtra() *GrowtopiaWorld_ContainmentFieldPowerNodeExtra {
	return &GrowtopiaWorld_ContainmentFieldPowerNodeExtra{
	}
}

func (this GrowtopiaWorld_ContainmentFieldPowerNodeExtra) IO_() *kaitai.Stream {
	return this._io
}

func (this *GrowtopiaWorld_ContainmentFieldPowerNodeExtra) Read(io *kaitai.Stream, parent *GrowtopiaWorld_WorldTile, root *GrowtopiaWorld) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp30, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.TimeMs = uint32(tmp30)
	tmp31, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.NumLinkedNodes = uint32(tmp31)
	for i := 0; i < int(this.NumLinkedNodes); i++ {
		_ = i
		tmp32, err := this._io.ReadU4le()
		if err != nil {
			return err
		}
		this.LinkedNodes = append(this.LinkedNodes, tmp32)
	}
	return err
}
type GrowtopiaWorld_CookingOvenExtra struct {
	TempLevel uint32
	IngredientListSize uint32
	Ingredients []*GrowtopiaWorld_CookingOvenExtra_Ingredient
	Unk1 uint32
	Unk2 uint32
	Unk3 uint32
	_io *kaitai.Stream
	_root *GrowtopiaWorld
	_parent *GrowtopiaWorld_WorldTile
}
func NewGrowtopiaWorld_CookingOvenExtra() *GrowtopiaWorld_CookingOvenExtra {
	return &GrowtopiaWorld_CookingOvenExtra{
	}
}

func (this GrowtopiaWorld_CookingOvenExtra) IO_() *kaitai.Stream {
	return this._io
}

func (this *GrowtopiaWorld_CookingOvenExtra) Read(io *kaitai.Stream, parent *GrowtopiaWorld_WorldTile, root *GrowtopiaWorld) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp33, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.TempLevel = uint32(tmp33)
	tmp34, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.IngredientListSize = uint32(tmp34)
	for i := 0; i < int(this.IngredientListSize / 2); i++ {
		_ = i
		tmp35 := NewGrowtopiaWorld_CookingOvenExtra_Ingredient()
		err = tmp35.Read(this._io, this, this._root)
		if err != nil {
			return err
		}
		this.Ingredients = append(this.Ingredients, tmp35)
	}
	tmp36, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.Unk1 = uint32(tmp36)
	tmp37, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.Unk2 = uint32(tmp37)
	tmp38, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.Unk3 = uint32(tmp38)
	return err
}
type GrowtopiaWorld_CookingOvenExtra_Ingredient struct {
	ItemId uint32
	TimeAdded uint32
	_io *kaitai.Stream
	_root *GrowtopiaWorld
	_parent *GrowtopiaWorld_CookingOvenExtra
}
func NewGrowtopiaWorld_CookingOvenExtra_Ingredient() *GrowtopiaWorld_CookingOvenExtra_Ingredient {
	return &GrowtopiaWorld_CookingOvenExtra_Ingredient{
	}
}

func (this GrowtopiaWorld_CookingOvenExtra_Ingredient) IO_() *kaitai.Stream {
	return this._io
}

func (this *GrowtopiaWorld_CookingOvenExtra_Ingredient) Read(io *kaitai.Stream, parent *GrowtopiaWorld_CookingOvenExtra, root *GrowtopiaWorld) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp39, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.ItemId = uint32(tmp39)
	tmp40, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.TimeAdded = uint32(tmp40)
	return err
}
type GrowtopiaWorld_CountryFlagExtra struct {
	Country *GrowtopiaWorld_GtStr
	_io *kaitai.Stream
	_root *GrowtopiaWorld
	_parent *GrowtopiaWorld_WorldTile
}
func NewGrowtopiaWorld_CountryFlagExtra() *GrowtopiaWorld_CountryFlagExtra {
	return &GrowtopiaWorld_CountryFlagExtra{
	}
}

func (this GrowtopiaWorld_CountryFlagExtra) IO_() *kaitai.Stream {
	return this._io
}

func (this *GrowtopiaWorld_CountryFlagExtra) Read(io *kaitai.Stream, parent *GrowtopiaWorld_WorldTile, root *GrowtopiaWorld) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	if (this._parent.Fg == 3394) {
		tmp41 := NewGrowtopiaWorld_GtStr()
		err = tmp41.Read(this._io, this, this._root)
		if err != nil {
			return err
		}
		this.Country = tmp41
	}
	return err
}
type GrowtopiaWorld_CrimeInProgressExtra struct {
	CrimeName *GrowtopiaWorld_GtStr
	CrimeIndex uint32
	Unk1 uint8
	_io *kaitai.Stream
	_root *GrowtopiaWorld
	_parent *GrowtopiaWorld_WorldTile
}
func NewGrowtopiaWorld_CrimeInProgressExtra() *GrowtopiaWorld_CrimeInProgressExtra {
	return &GrowtopiaWorld_CrimeInProgressExtra{
	}
}

func (this GrowtopiaWorld_CrimeInProgressExtra) IO_() *kaitai.Stream {
	return this._io
}

func (this *GrowtopiaWorld_CrimeInProgressExtra) Read(io *kaitai.Stream, parent *GrowtopiaWorld_WorldTile, root *GrowtopiaWorld) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp42 := NewGrowtopiaWorld_GtStr()
	err = tmp42.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.CrimeName = tmp42
	tmp43, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.CrimeIndex = uint32(tmp43)
	tmp44, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.Unk1 = tmp44
	return err
}
type GrowtopiaWorld_CrystalExtra struct {
	NumCrystals uint16
	Crystals []uint8
	_io *kaitai.Stream
	_root *GrowtopiaWorld
	_parent *GrowtopiaWorld_WorldTile
}
func NewGrowtopiaWorld_CrystalExtra() *GrowtopiaWorld_CrystalExtra {
	return &GrowtopiaWorld_CrystalExtra{
	}
}

func (this GrowtopiaWorld_CrystalExtra) IO_() *kaitai.Stream {
	return this._io
}

func (this *GrowtopiaWorld_CrystalExtra) Read(io *kaitai.Stream, parent *GrowtopiaWorld_WorldTile, root *GrowtopiaWorld) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp45, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.NumCrystals = uint16(tmp45)
	for i := 0; i < int(this.NumCrystals); i++ {
		_ = i
		tmp46, err := this._io.ReadU1()
		if err != nil {
			return err
		}
		this.Crystals = append(this.Crystals, tmp46)
	}
	return err
}
type GrowtopiaWorld_CybotExtra struct {
	NumCommands uint32
	Commands []*GrowtopiaWorld_CybotExtra_Command
	Timer uint32
	IsActivated uint32
	_io *kaitai.Stream
	_root *GrowtopiaWorld
	_parent *GrowtopiaWorld_WorldTile
}
func NewGrowtopiaWorld_CybotExtra() *GrowtopiaWorld_CybotExtra {
	return &GrowtopiaWorld_CybotExtra{
	}
}

func (this GrowtopiaWorld_CybotExtra) IO_() *kaitai.Stream {
	return this._io
}

func (this *GrowtopiaWorld_CybotExtra) Read(io *kaitai.Stream, parent *GrowtopiaWorld_WorldTile, root *GrowtopiaWorld) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp47, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.NumCommands = uint32(tmp47)
	for i := 0; i < int(this.NumCommands); i++ {
		_ = i
		tmp48 := NewGrowtopiaWorld_CybotExtra_Command()
		err = tmp48.Read(this._io, this, this._root)
		if err != nil {
			return err
		}
		this.Commands = append(this.Commands, tmp48)
	}
	tmp49, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.Timer = uint32(tmp49)
	tmp50, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.IsActivated = uint32(tmp50)
	return err
}
type GrowtopiaWorld_CybotExtra_Command struct {
	CommandId uint32
	IsCommandUsed uint32
	Unk1 []byte
	_io *kaitai.Stream
	_root *GrowtopiaWorld
	_parent *GrowtopiaWorld_CybotExtra
}
func NewGrowtopiaWorld_CybotExtra_Command() *GrowtopiaWorld_CybotExtra_Command {
	return &GrowtopiaWorld_CybotExtra_Command{
	}
}

func (this GrowtopiaWorld_CybotExtra_Command) IO_() *kaitai.Stream {
	return this._io
}

func (this *GrowtopiaWorld_CybotExtra_Command) Read(io *kaitai.Stream, parent *GrowtopiaWorld_CybotExtra, root *GrowtopiaWorld) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp51, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.CommandId = uint32(tmp51)
	tmp52, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.IsCommandUsed = uint32(tmp52)
	tmp53, err := this._io.ReadBytes(int(7))
	if err != nil {
		return err
	}
	tmp53 = tmp53
	this.Unk1 = tmp53
	return err
}
type GrowtopiaWorld_DataBedrockExtra struct {
	Unk1 []byte
	Pad1 []byte
	_io *kaitai.Stream
	_root *GrowtopiaWorld
	_parent *GrowtopiaWorld_WorldTile
}
func NewGrowtopiaWorld_DataBedrockExtra() *GrowtopiaWorld_DataBedrockExtra {
	return &GrowtopiaWorld_DataBedrockExtra{
	}
}

func (this GrowtopiaWorld_DataBedrockExtra) IO_() *kaitai.Stream {
	return this._io
}

func (this *GrowtopiaWorld_DataBedrockExtra) Read(io *kaitai.Stream, parent *GrowtopiaWorld_WorldTile, root *GrowtopiaWorld) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp54, err := this._io.ReadBytes(int(17))
	if err != nil {
		return err
	}
	tmp54 = tmp54
	this.Unk1 = tmp54
	tmp55, err := this._io.ReadBytes(int(4))
	if err != nil {
		return err
	}
	tmp55 = tmp55
	this.Pad1 = tmp55
	return err
}
type GrowtopiaWorld_DiceExtra struct {
	Symbol uint8
	_io *kaitai.Stream
	_root *GrowtopiaWorld
	_parent *GrowtopiaWorld_WorldTile
}
func NewGrowtopiaWorld_DiceExtra() *GrowtopiaWorld_DiceExtra {
	return &GrowtopiaWorld_DiceExtra{
	}
}

func (this GrowtopiaWorld_DiceExtra) IO_() *kaitai.Stream {
	return this._io
}

func (this *GrowtopiaWorld_DiceExtra) Read(io *kaitai.Stream, parent *GrowtopiaWorld_WorldTile, root *GrowtopiaWorld) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp56, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.Symbol = tmp56
	return err
}
type GrowtopiaWorld_DisplayBlockExtra struct {
	ItemId uint32
	_io *kaitai.Stream
	_root *GrowtopiaWorld
	_parent *GrowtopiaWorld_WorldTile
}
func NewGrowtopiaWorld_DisplayBlockExtra() *GrowtopiaWorld_DisplayBlockExtra {
	return &GrowtopiaWorld_DisplayBlockExtra{
	}
}

func (this GrowtopiaWorld_DisplayBlockExtra) IO_() *kaitai.Stream {
	return this._io
}

func (this *GrowtopiaWorld_DisplayBlockExtra) Read(io *kaitai.Stream, parent *GrowtopiaWorld_WorldTile, root *GrowtopiaWorld) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp57, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.ItemId = uint32(tmp57)
	return err
}
type GrowtopiaWorld_DnaExtractorExtra struct {
	_io *kaitai.Stream
	_root *GrowtopiaWorld
	_parent *GrowtopiaWorld_WorldTile
}
func NewGrowtopiaWorld_DnaExtractorExtra() *GrowtopiaWorld_DnaExtractorExtra {
	return &GrowtopiaWorld_DnaExtractorExtra{
	}
}

func (this GrowtopiaWorld_DnaExtractorExtra) IO_() *kaitai.Stream {
	return this._io
}

func (this *GrowtopiaWorld_DnaExtractorExtra) Read(io *kaitai.Stream, parent *GrowtopiaWorld_WorldTile, root *GrowtopiaWorld) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	return err
}
type GrowtopiaWorld_DoorExtra struct {
	Label *GrowtopiaWorld_GtStr
	Flags uint8
	_io *kaitai.Stream
	_root *GrowtopiaWorld
	_parent *GrowtopiaWorld_WorldTile
}
func NewGrowtopiaWorld_DoorExtra() *GrowtopiaWorld_DoorExtra {
	return &GrowtopiaWorld_DoorExtra{
	}
}

func (this GrowtopiaWorld_DoorExtra) IO_() *kaitai.Stream {
	return this._io
}

func (this *GrowtopiaWorld_DoorExtra) Read(io *kaitai.Stream, parent *GrowtopiaWorld_WorldTile, root *GrowtopiaWorld) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp58 := NewGrowtopiaWorld_GtStr()
	err = tmp58.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.Label = tmp58
	tmp59, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.Flags = tmp59
	return err
}
type GrowtopiaWorld_FishTankPortExtra struct {
	Flags uint8
	FishDataLength uint32
	Fishes []*GrowtopiaWorld_FishTankPortExtra_FishInfo
	_io *kaitai.Stream
	_root *GrowtopiaWorld
	_parent *GrowtopiaWorld_WorldTile
}
func NewGrowtopiaWorld_FishTankPortExtra() *GrowtopiaWorld_FishTankPortExtra {
	return &GrowtopiaWorld_FishTankPortExtra{
	}
}

func (this GrowtopiaWorld_FishTankPortExtra) IO_() *kaitai.Stream {
	return this._io
}

func (this *GrowtopiaWorld_FishTankPortExtra) Read(io *kaitai.Stream, parent *GrowtopiaWorld_WorldTile, root *GrowtopiaWorld) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp60, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.Flags = tmp60
	tmp61, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.FishDataLength = uint32(tmp61)
	for i := 0; i < int(this.FishDataLength / 2); i++ {
		_ = i
		tmp62 := NewGrowtopiaWorld_FishTankPortExtra_FishInfo()
		err = tmp62.Read(this._io, this, this._root)
		if err != nil {
			return err
		}
		this.Fishes = append(this.Fishes, tmp62)
	}
	return err
}
type GrowtopiaWorld_FishTankPortExtra_FishInfo struct {
	ItemId uint32
	Lbs uint32
	_io *kaitai.Stream
	_root *GrowtopiaWorld
	_parent *GrowtopiaWorld_FishTankPortExtra
}
func NewGrowtopiaWorld_FishTankPortExtra_FishInfo() *GrowtopiaWorld_FishTankPortExtra_FishInfo {
	return &GrowtopiaWorld_FishTankPortExtra_FishInfo{
	}
}

func (this GrowtopiaWorld_FishTankPortExtra_FishInfo) IO_() *kaitai.Stream {
	return this._io
}

func (this *GrowtopiaWorld_FishTankPortExtra_FishInfo) Read(io *kaitai.Stream, parent *GrowtopiaWorld_FishTankPortExtra, root *GrowtopiaWorld) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp63, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.ItemId = uint32(tmp63)
	tmp64, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.Lbs = uint32(tmp64)
	return err
}
type GrowtopiaWorld_FishWallMountExtra struct {
	Label *GrowtopiaWorld_GtStr
	ItemId uint32
	Lbs uint8
	_io *kaitai.Stream
	_root *GrowtopiaWorld
	_parent *GrowtopiaWorld_WorldTile
}
func NewGrowtopiaWorld_FishWallMountExtra() *GrowtopiaWorld_FishWallMountExtra {
	return &GrowtopiaWorld_FishWallMountExtra{
	}
}

func (this GrowtopiaWorld_FishWallMountExtra) IO_() *kaitai.Stream {
	return this._io
}

func (this *GrowtopiaWorld_FishWallMountExtra) Read(io *kaitai.Stream, parent *GrowtopiaWorld_WorldTile, root *GrowtopiaWorld) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp65 := NewGrowtopiaWorld_GtStr()
	err = tmp65.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.Label = tmp65
	tmp66, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.ItemId = uint32(tmp66)
	tmp67, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.Lbs = tmp67
	return err
}
type GrowtopiaWorld_ForgeExtra struct {
	Temperature uint32
	_io *kaitai.Stream
	_root *GrowtopiaWorld
	_parent *GrowtopiaWorld_WorldTile
}
func NewGrowtopiaWorld_ForgeExtra() *GrowtopiaWorld_ForgeExtra {
	return &GrowtopiaWorld_ForgeExtra{
	}
}

func (this GrowtopiaWorld_ForgeExtra) IO_() *kaitai.Stream {
	return this._io
}

func (this *GrowtopiaWorld_ForgeExtra) Read(io *kaitai.Stream, parent *GrowtopiaWorld_WorldTile, root *GrowtopiaWorld) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp68, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.Temperature = uint32(tmp68)
	return err
}
type GrowtopiaWorld_FossilPrepStationExtra struct {
	Unk1 uint32
	_io *kaitai.Stream
	_root *GrowtopiaWorld
	_parent *GrowtopiaWorld_WorldTile
}
func NewGrowtopiaWorld_FossilPrepStationExtra() *GrowtopiaWorld_FossilPrepStationExtra {
	return &GrowtopiaWorld_FossilPrepStationExtra{
	}
}

func (this GrowtopiaWorld_FossilPrepStationExtra) IO_() *kaitai.Stream {
	return this._io
}

func (this *GrowtopiaWorld_FossilPrepStationExtra) Read(io *kaitai.Stream, parent *GrowtopiaWorld_WorldTile, root *GrowtopiaWorld) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp69, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.Unk1 = uint32(tmp69)
	return err
}
type GrowtopiaWorld_FriendsEntranceExtra struct {
	OwnerUserid uint32
	Unk1 []byte
	NumAllowedFriendsUserid uint16
	AllowedFriendsUserid []uint32
	_io *kaitai.Stream
	_root *GrowtopiaWorld
	_parent *GrowtopiaWorld_WorldTile
}
func NewGrowtopiaWorld_FriendsEntranceExtra() *GrowtopiaWorld_FriendsEntranceExtra {
	return &GrowtopiaWorld_FriendsEntranceExtra{
	}
}

func (this GrowtopiaWorld_FriendsEntranceExtra) IO_() *kaitai.Stream {
	return this._io
}

func (this *GrowtopiaWorld_FriendsEntranceExtra) Read(io *kaitai.Stream, parent *GrowtopiaWorld_WorldTile, root *GrowtopiaWorld) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp70, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.OwnerUserid = uint32(tmp70)
	tmp71, err := this._io.ReadBytes(int(2))
	if err != nil {
		return err
	}
	tmp71 = tmp71
	this.Unk1 = tmp71
	tmp72, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.NumAllowedFriendsUserid = uint16(tmp72)
	for i := 0; i < int(this.NumAllowedFriendsUserid); i++ {
		_ = i
		tmp73, err := this._io.ReadU4le()
		if err != nil {
			return err
		}
		this.AllowedFriendsUserid = append(this.AllowedFriendsUserid, tmp73)
	}
	return err
}
type GrowtopiaWorld_GameGeneratorExtra struct {
	_io *kaitai.Stream
	_root *GrowtopiaWorld
	_parent *GrowtopiaWorld_WorldTile
}
func NewGrowtopiaWorld_GameGeneratorExtra() *GrowtopiaWorld_GameGeneratorExtra {
	return &GrowtopiaWorld_GameGeneratorExtra{
	}
}

func (this GrowtopiaWorld_GameGeneratorExtra) IO_() *kaitai.Stream {
	return this._io
}

func (this *GrowtopiaWorld_GameGeneratorExtra) Read(io *kaitai.Stream, parent *GrowtopiaWorld_WorldTile, root *GrowtopiaWorld) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	return err
}
type GrowtopiaWorld_GameGraveExtra struct {
	TeamId uint8
	_io *kaitai.Stream
	_root *GrowtopiaWorld
	_parent *GrowtopiaWorld_WorldTile
}
func NewGrowtopiaWorld_GameGraveExtra() *GrowtopiaWorld_GameGraveExtra {
	return &GrowtopiaWorld_GameGraveExtra{
	}
}

func (this GrowtopiaWorld_GameGraveExtra) IO_() *kaitai.Stream {
	return this._io
}

func (this *GrowtopiaWorld_GameGraveExtra) Read(io *kaitai.Stream, parent *GrowtopiaWorld_WorldTile, root *GrowtopiaWorld) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp74, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.TeamId = tmp74
	return err
}
type GrowtopiaWorld_GeigerChargerExtra struct {
	Unk1 []byte
	_io *kaitai.Stream
	_root *GrowtopiaWorld
	_parent *GrowtopiaWorld_WorldTile
}
func NewGrowtopiaWorld_GeigerChargerExtra() *GrowtopiaWorld_GeigerChargerExtra {
	return &GrowtopiaWorld_GeigerChargerExtra{
	}
}

func (this GrowtopiaWorld_GeigerChargerExtra) IO_() *kaitai.Stream {
	return this._io
}

func (this *GrowtopiaWorld_GeigerChargerExtra) Read(io *kaitai.Stream, parent *GrowtopiaWorld_WorldTile, root *GrowtopiaWorld) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp75, err := this._io.ReadBytes(int(4))
	if err != nil {
		return err
	}
	tmp75 = tmp75
	this.Unk1 = tmp75
	return err
}
type GrowtopiaWorld_GivingTreeExtra struct {
	Harvested uint8
	Age uint16
	Unk1 uint16
	DecorationPercentage uint8
	_io *kaitai.Stream
	_root *GrowtopiaWorld
	_parent *GrowtopiaWorld_WorldTile
}
func NewGrowtopiaWorld_GivingTreeExtra() *GrowtopiaWorld_GivingTreeExtra {
	return &GrowtopiaWorld_GivingTreeExtra{
	}
}

func (this GrowtopiaWorld_GivingTreeExtra) IO_() *kaitai.Stream {
	return this._io
}

func (this *GrowtopiaWorld_GivingTreeExtra) Read(io *kaitai.Stream, parent *GrowtopiaWorld_WorldTile, root *GrowtopiaWorld) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp76, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.Harvested = tmp76
	tmp77, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.Age = uint16(tmp77)
	tmp78, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.Unk1 = uint16(tmp78)
	tmp79, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.DecorationPercentage = tmp79
	return err
}
type GrowtopiaWorld_GrowscanExtra struct {
	Unk1 uint8
	_io *kaitai.Stream
	_root *GrowtopiaWorld
	_parent *GrowtopiaWorld_WorldTile
}
func NewGrowtopiaWorld_GrowscanExtra() *GrowtopiaWorld_GrowscanExtra {
	return &GrowtopiaWorld_GrowscanExtra{
	}
}

func (this GrowtopiaWorld_GrowscanExtra) IO_() *kaitai.Stream {
	return this._io
}

func (this *GrowtopiaWorld_GrowscanExtra) Read(io *kaitai.Stream, parent *GrowtopiaWorld_WorldTile, root *GrowtopiaWorld) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp80, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.Unk1 = tmp80
	return err
}
type GrowtopiaWorld_GtStr struct {
	LenData uint16
	Str string
	_io *kaitai.Stream
	_root *GrowtopiaWorld
	_parent kaitai.Struct
}
func NewGrowtopiaWorld_GtStr() *GrowtopiaWorld_GtStr {
	return &GrowtopiaWorld_GtStr{
	}
}

func (this GrowtopiaWorld_GtStr) IO_() *kaitai.Stream {
	return this._io
}

func (this *GrowtopiaWorld_GtStr) Read(io *kaitai.Stream, parent kaitai.Struct, root *GrowtopiaWorld) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp81, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.LenData = uint16(tmp81)
	tmp82, err := this._io.ReadBytes(int(this.LenData))
	if err != nil {
		return err
	}
	tmp82 = tmp82
	this.Str = string(tmp82)
	return err
}
type GrowtopiaWorld_GuildExtra struct {
	Unk1 uint8
	GuildId uint32
	GuildMascotFg uint16
	GuildMascotBg uint16
	GuildLevel uint32
	GuildFlags uint32
	_io *kaitai.Stream
	_root *GrowtopiaWorld
	_parent *GrowtopiaWorld_WorldTile
}
func NewGrowtopiaWorld_GuildExtra() *GrowtopiaWorld_GuildExtra {
	return &GrowtopiaWorld_GuildExtra{
	}
}

func (this GrowtopiaWorld_GuildExtra) IO_() *kaitai.Stream {
	return this._io
}

func (this *GrowtopiaWorld_GuildExtra) Read(io *kaitai.Stream, parent *GrowtopiaWorld_WorldTile, root *GrowtopiaWorld) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp83, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.Unk1 = tmp83
	tmp84, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.GuildId = uint32(tmp84)
	tmp85, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.GuildMascotFg = uint16(tmp85)
	tmp86, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.GuildMascotBg = uint16(tmp86)
	tmp87, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.GuildLevel = uint32(tmp87)
	tmp88, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.GuildFlags = uint32(tmp88)
	return err
}
type GrowtopiaWorld_HeartMonitorExtra struct {
	UserId uint32
	GrowId *GrowtopiaWorld_GtStr
	_io *kaitai.Stream
	_root *GrowtopiaWorld
	_parent *GrowtopiaWorld_WorldTile
}
func NewGrowtopiaWorld_HeartMonitorExtra() *GrowtopiaWorld_HeartMonitorExtra {
	return &GrowtopiaWorld_HeartMonitorExtra{
	}
}

func (this GrowtopiaWorld_HeartMonitorExtra) IO_() *kaitai.Stream {
	return this._io
}

func (this *GrowtopiaWorld_HeartMonitorExtra) Read(io *kaitai.Stream, parent *GrowtopiaWorld_WorldTile, root *GrowtopiaWorld) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp89, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.UserId = uint32(tmp89)
	tmp90 := NewGrowtopiaWorld_GtStr()
	err = tmp90.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.GrowId = tmp90
	return err
}
type GrowtopiaWorld_HowlerExtra struct {
	_io *kaitai.Stream
	_root *GrowtopiaWorld
	_parent *GrowtopiaWorld_WorldTile
}
func NewGrowtopiaWorld_HowlerExtra() *GrowtopiaWorld_HowlerExtra {
	return &GrowtopiaWorld_HowlerExtra{
	}
}

func (this GrowtopiaWorld_HowlerExtra) IO_() *kaitai.Stream {
	return this._io
}

func (this *GrowtopiaWorld_HowlerExtra) Read(io *kaitai.Stream, parent *GrowtopiaWorld_WorldTile, root *GrowtopiaWorld) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	return err
}
type GrowtopiaWorld_InfinityWeatherMachineExtra struct {
	IntervalMins uint32
	NumWeatherMachines uint32
	WeatherMachines []uint32
	_io *kaitai.Stream
	_root *GrowtopiaWorld
	_parent *GrowtopiaWorld_WorldTile
}
func NewGrowtopiaWorld_InfinityWeatherMachineExtra() *GrowtopiaWorld_InfinityWeatherMachineExtra {
	return &GrowtopiaWorld_InfinityWeatherMachineExtra{
	}
}

func (this GrowtopiaWorld_InfinityWeatherMachineExtra) IO_() *kaitai.Stream {
	return this._io
}

func (this *GrowtopiaWorld_InfinityWeatherMachineExtra) Read(io *kaitai.Stream, parent *GrowtopiaWorld_WorldTile, root *GrowtopiaWorld) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp91, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.IntervalMins = uint32(tmp91)
	tmp92, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.NumWeatherMachines = uint32(tmp92)
	for i := 0; i < int(this.NumWeatherMachines); i++ {
		_ = i
		tmp93, err := this._io.ReadU4le()
		if err != nil {
			return err
		}
		this.WeatherMachines = append(this.WeatherMachines, tmp93)
	}
	return err
}
type GrowtopiaWorld_ItemSuckerExtra struct {
	ItemId uint32
	ItemAmount uint32
	Flags uint16
	ItemLimit uint32
	_io *kaitai.Stream
	_root *GrowtopiaWorld
	_parent *GrowtopiaWorld_WorldTile
}
func NewGrowtopiaWorld_ItemSuckerExtra() *GrowtopiaWorld_ItemSuckerExtra {
	return &GrowtopiaWorld_ItemSuckerExtra{
	}
}

func (this GrowtopiaWorld_ItemSuckerExtra) IO_() *kaitai.Stream {
	return this._io
}

func (this *GrowtopiaWorld_ItemSuckerExtra) Read(io *kaitai.Stream, parent *GrowtopiaWorld_WorldTile, root *GrowtopiaWorld) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp94, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.ItemId = uint32(tmp94)
	tmp95, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.ItemAmount = uint32(tmp95)
	tmp96, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.Flags = uint16(tmp96)
	tmp97, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.ItemLimit = uint32(tmp97)
	return err
}
type GrowtopiaWorld_KrakensGalaticBlockExtra struct {
	PatternNumber uint8
	Unk1 []byte
	ColorRgb []byte
	_io *kaitai.Stream
	_root *GrowtopiaWorld
	_parent *GrowtopiaWorld_WorldTile
}
func NewGrowtopiaWorld_KrakensGalaticBlockExtra() *GrowtopiaWorld_KrakensGalaticBlockExtra {
	return &GrowtopiaWorld_KrakensGalaticBlockExtra{
	}
}

func (this GrowtopiaWorld_KrakensGalaticBlockExtra) IO_() *kaitai.Stream {
	return this._io
}

func (this *GrowtopiaWorld_KrakensGalaticBlockExtra) Read(io *kaitai.Stream, parent *GrowtopiaWorld_WorldTile, root *GrowtopiaWorld) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp98, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.PatternNumber = tmp98
	tmp99, err := this._io.ReadBytes(int(4))
	if err != nil {
		return err
	}
	tmp99 = tmp99
	this.Unk1 = tmp99
	tmp100, err := this._io.ReadBytes(int(3))
	if err != nil {
		return err
	}
	tmp100 = tmp100
	this.ColorRgb = tmp100
	return err
}
type GrowtopiaWorld_LobsterTrapExtra struct {
	_io *kaitai.Stream
	_root *GrowtopiaWorld
	_parent *GrowtopiaWorld_WorldTile
}
func NewGrowtopiaWorld_LobsterTrapExtra() *GrowtopiaWorld_LobsterTrapExtra {
	return &GrowtopiaWorld_LobsterTrapExtra{
	}
}

func (this GrowtopiaWorld_LobsterTrapExtra) IO_() *kaitai.Stream {
	return this._io
}

func (this *GrowtopiaWorld_LobsterTrapExtra) Read(io *kaitai.Stream, parent *GrowtopiaWorld_WorldTile, root *GrowtopiaWorld) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	return err
}
type GrowtopiaWorld_LockBotExtra struct {
	Age uint32
	_io *kaitai.Stream
	_root *GrowtopiaWorld
	_parent *GrowtopiaWorld_WorldTile
}
func NewGrowtopiaWorld_LockBotExtra() *GrowtopiaWorld_LockBotExtra {
	return &GrowtopiaWorld_LockBotExtra{
	}
}

func (this GrowtopiaWorld_LockBotExtra) IO_() *kaitai.Stream {
	return this._io
}

func (this *GrowtopiaWorld_LockBotExtra) Read(io *kaitai.Stream, parent *GrowtopiaWorld_WorldTile, root *GrowtopiaWorld) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp101, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.Age = uint32(tmp101)
	return err
}
type GrowtopiaWorld_LockExtra struct {
	Flag uint8
	OwnerUserId uint32
	NumAuthorizedUserids uint32
	AuthorizedUserids []int32
	MinimumLevel uint32
	WorldTimer uint32
	GuildId uint32
	GuildMascotFg uint16
	GuildMascotBg uint16
	GuildLevel uint32
	GuildFlags uint32
	_io *kaitai.Stream
	_root *GrowtopiaWorld
	_parent *GrowtopiaWorld_WorldTile
}
func NewGrowtopiaWorld_LockExtra() *GrowtopiaWorld_LockExtra {
	return &GrowtopiaWorld_LockExtra{
	}
}

func (this GrowtopiaWorld_LockExtra) IO_() *kaitai.Stream {
	return this._io
}

func (this *GrowtopiaWorld_LockExtra) Read(io *kaitai.Stream, parent *GrowtopiaWorld_WorldTile, root *GrowtopiaWorld) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp102, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.Flag = tmp102
	tmp103, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.OwnerUserId = uint32(tmp103)
	tmp104, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.NumAuthorizedUserids = uint32(tmp104)
	for i := 0; i < int(this.NumAuthorizedUserids); i++ {
		_ = i
		tmp105, err := this._io.ReadS4le()
		if err != nil {
			return err
		}
		this.AuthorizedUserids = append(this.AuthorizedUserids, tmp105)
	}
	tmp106, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.MinimumLevel = uint32(tmp106)
	tmp107, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.WorldTimer = uint32(tmp107)
	if (this._parent.Fg == 5814) {
		tmp108, err := this._io.ReadU4le()
		if err != nil {
			return err
		}
		this.GuildId = uint32(tmp108)
	}
	if (this._parent.Fg == 5814) {
		tmp109, err := this._io.ReadU2le()
		if err != nil {
			return err
		}
		this.GuildMascotFg = uint16(tmp109)
	}
	if (this._parent.Fg == 5814) {
		tmp110, err := this._io.ReadU2le()
		if err != nil {
			return err
		}
		this.GuildMascotBg = uint16(tmp110)
	}
	if (this._parent.Fg == 5814) {
		tmp111, err := this._io.ReadU4le()
		if err != nil {
			return err
		}
		this.GuildLevel = uint32(tmp111)
	}
	if (this._parent.Fg == 5814) {
		tmp112, err := this._io.ReadU4le()
		if err != nil {
			return err
		}
		this.GuildFlags = uint32(tmp112)
	}
	return err
}

/**
 * if you encounter negative user id, it is a world BPM. Kaitai doesnt support
 * complex logic yet. 
 */
type GrowtopiaWorld_MagicEggExtra struct {
	EggAmount uint32
	_io *kaitai.Stream
	_root *GrowtopiaWorld
	_parent *GrowtopiaWorld_WorldTile
}
func NewGrowtopiaWorld_MagicEggExtra() *GrowtopiaWorld_MagicEggExtra {
	return &GrowtopiaWorld_MagicEggExtra{
	}
}

func (this GrowtopiaWorld_MagicEggExtra) IO_() *kaitai.Stream {
	return this._io
}

func (this *GrowtopiaWorld_MagicEggExtra) Read(io *kaitai.Stream, parent *GrowtopiaWorld_WorldTile, root *GrowtopiaWorld) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp113, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.EggAmount = uint32(tmp113)
	return err
}
type GrowtopiaWorld_MannequinExtra struct {
	Label *GrowtopiaWorld_GtStr
	Unk1 uint8
	Unk2 uint16
	Unk3 uint16
	Hat uint16
	Shirt uint16
	Pants uint16
	Boots uint16
	Face uint16
	Hand uint16
	Back uint16
	Hair uint16
	Neck uint16
	_io *kaitai.Stream
	_root *GrowtopiaWorld
	_parent *GrowtopiaWorld_WorldTile
}
func NewGrowtopiaWorld_MannequinExtra() *GrowtopiaWorld_MannequinExtra {
	return &GrowtopiaWorld_MannequinExtra{
	}
}

func (this GrowtopiaWorld_MannequinExtra) IO_() *kaitai.Stream {
	return this._io
}

func (this *GrowtopiaWorld_MannequinExtra) Read(io *kaitai.Stream, parent *GrowtopiaWorld_WorldTile, root *GrowtopiaWorld) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp114 := NewGrowtopiaWorld_GtStr()
	err = tmp114.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.Label = tmp114
	tmp115, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.Unk1 = tmp115
	tmp116, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.Unk2 = uint16(tmp116)
	tmp117, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.Unk3 = uint16(tmp117)
	tmp118, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.Hat = uint16(tmp118)
	tmp119, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.Shirt = uint16(tmp119)
	tmp120, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.Pants = uint16(tmp120)
	tmp121, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.Boots = uint16(tmp121)
	tmp122, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.Face = uint16(tmp122)
	tmp123, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.Hand = uint16(tmp123)
	tmp124, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.Back = uint16(tmp124)
	tmp125, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.Hair = uint16(tmp125)
	tmp126, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.Neck = uint16(tmp126)
	return err
}
type GrowtopiaWorld_PaintingEaselExtra struct {
	ItemId uint32
	Label *GrowtopiaWorld_GtStr
	_io *kaitai.Stream
	_root *GrowtopiaWorld
	_parent *GrowtopiaWorld_WorldTile
}
func NewGrowtopiaWorld_PaintingEaselExtra() *GrowtopiaWorld_PaintingEaselExtra {
	return &GrowtopiaWorld_PaintingEaselExtra{
	}
}

func (this GrowtopiaWorld_PaintingEaselExtra) IO_() *kaitai.Stream {
	return this._io
}

func (this *GrowtopiaWorld_PaintingEaselExtra) Read(io *kaitai.Stream, parent *GrowtopiaWorld_WorldTile, root *GrowtopiaWorld) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp127, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.ItemId = uint32(tmp127)
	tmp128 := NewGrowtopiaWorld_GtStr()
	err = tmp128.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.Label = tmp128
	return err
}
type GrowtopiaWorld_PetBattleCageExtra struct {
	Label *GrowtopiaWorld_GtStr
	BasePet uint32
	CombinedPet1 uint32
	CombinedPet2 uint32
	_io *kaitai.Stream
	_root *GrowtopiaWorld
	_parent *GrowtopiaWorld_WorldTile
}
func NewGrowtopiaWorld_PetBattleCageExtra() *GrowtopiaWorld_PetBattleCageExtra {
	return &GrowtopiaWorld_PetBattleCageExtra{
	}
}

func (this GrowtopiaWorld_PetBattleCageExtra) IO_() *kaitai.Stream {
	return this._io
}

func (this *GrowtopiaWorld_PetBattleCageExtra) Read(io *kaitai.Stream, parent *GrowtopiaWorld_WorldTile, root *GrowtopiaWorld) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp129 := NewGrowtopiaWorld_GtStr()
	err = tmp129.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.Label = tmp129
	tmp130, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.BasePet = uint32(tmp130)
	tmp131, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.CombinedPet1 = uint32(tmp131)
	tmp132, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.CombinedPet2 = uint32(tmp132)
	return err
}
type GrowtopiaWorld_PetTrainerExtra struct {
	Name *GrowtopiaWorld_GtStr
	NumPets uint32
	Unk1 uint32
	Pets []uint32
	_io *kaitai.Stream
	_root *GrowtopiaWorld
	_parent *GrowtopiaWorld_WorldTile
}
func NewGrowtopiaWorld_PetTrainerExtra() *GrowtopiaWorld_PetTrainerExtra {
	return &GrowtopiaWorld_PetTrainerExtra{
	}
}

func (this GrowtopiaWorld_PetTrainerExtra) IO_() *kaitai.Stream {
	return this._io
}

func (this *GrowtopiaWorld_PetTrainerExtra) Read(io *kaitai.Stream, parent *GrowtopiaWorld_WorldTile, root *GrowtopiaWorld) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp133 := NewGrowtopiaWorld_GtStr()
	err = tmp133.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.Name = tmp133
	tmp134, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.NumPets = uint32(tmp134)
	tmp135, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.Unk1 = uint32(tmp135)
	for i := 0; i < int(this.NumPets); i++ {
		_ = i
		tmp136, err := this._io.ReadU4le()
		if err != nil {
			return err
		}
		this.Pets = append(this.Pets, tmp136)
	}
	return err
}
type GrowtopiaWorld_PhoneBoothExtra struct {
	Hat uint16
	Shirt uint16
	Pants uint16
	Shoes uint16
	Face uint16
	Hand uint16
	Back uint16
	Hair uint16
	Neck uint16
	_io *kaitai.Stream
	_root *GrowtopiaWorld
	_parent *GrowtopiaWorld_WorldTile
}
func NewGrowtopiaWorld_PhoneBoothExtra() *GrowtopiaWorld_PhoneBoothExtra {
	return &GrowtopiaWorld_PhoneBoothExtra{
	}
}

func (this GrowtopiaWorld_PhoneBoothExtra) IO_() *kaitai.Stream {
	return this._io
}

func (this *GrowtopiaWorld_PhoneBoothExtra) Read(io *kaitai.Stream, parent *GrowtopiaWorld_WorldTile, root *GrowtopiaWorld) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp137, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.Hat = uint16(tmp137)
	tmp138, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.Shirt = uint16(tmp138)
	tmp139, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.Pants = uint16(tmp139)
	tmp140, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.Shoes = uint16(tmp140)
	tmp141, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.Face = uint16(tmp141)
	tmp142, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.Hand = uint16(tmp142)
	tmp143, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.Back = uint16(tmp143)
	tmp144, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.Hair = uint16(tmp144)
	tmp145, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.Neck = uint16(tmp145)
	return err
}
type GrowtopiaWorld_PineappleGuzzlerExtra struct {
	PineappleFed uint32
	_io *kaitai.Stream
	_root *GrowtopiaWorld
	_parent *GrowtopiaWorld_WorldTile
}
func NewGrowtopiaWorld_PineappleGuzzlerExtra() *GrowtopiaWorld_PineappleGuzzlerExtra {
	return &GrowtopiaWorld_PineappleGuzzlerExtra{
	}
}

func (this GrowtopiaWorld_PineappleGuzzlerExtra) IO_() *kaitai.Stream {
	return this._io
}

func (this *GrowtopiaWorld_PineappleGuzzlerExtra) Read(io *kaitai.Stream, parent *GrowtopiaWorld_WorldTile, root *GrowtopiaWorld) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp146, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.PineappleFed = uint32(tmp146)
	return err
}
type GrowtopiaWorld_PortraitExtra struct {
	Label *GrowtopiaWorld_GtStr
	Unk1 uint32
	Unk2 uint32
	Unk3 []byte
	Unk4 uint8
	Unk5 uint16
	Face uint16
	Hat uint16
	Hair uint16
	Unk6 uint32
	InfinityCrownData *GrowtopiaWorld_GtStr
	_io *kaitai.Stream
	_root *GrowtopiaWorld
	_parent *GrowtopiaWorld_WorldTile
}
func NewGrowtopiaWorld_PortraitExtra() *GrowtopiaWorld_PortraitExtra {
	return &GrowtopiaWorld_PortraitExtra{
	}
}

func (this GrowtopiaWorld_PortraitExtra) IO_() *kaitai.Stream {
	return this._io
}

func (this *GrowtopiaWorld_PortraitExtra) Read(io *kaitai.Stream, parent *GrowtopiaWorld_WorldTile, root *GrowtopiaWorld) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp147 := NewGrowtopiaWorld_GtStr()
	err = tmp147.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.Label = tmp147
	tmp148, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.Unk1 = uint32(tmp148)
	tmp149, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.Unk2 = uint32(tmp149)
	tmp150, err := this._io.ReadBytes(int(5))
	if err != nil {
		return err
	}
	tmp150 = tmp150
	this.Unk3 = tmp150
	tmp151, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.Unk4 = tmp151
	tmp152, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.Unk5 = uint16(tmp152)
	tmp153, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.Face = uint16(tmp153)
	tmp154, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.Hat = uint16(tmp154)
	tmp155, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.Hair = uint16(tmp155)
	tmp156, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.Unk6 = uint32(tmp156)
	if (this.Hat == 12958) {
		tmp157 := NewGrowtopiaWorld_GtStr()
		err = tmp157.Read(this._io, this, this._root)
		if err != nil {
			return err
		}
		this.InfinityCrownData = tmp157
	}
	return err
}
type GrowtopiaWorld_ProviderExtra struct {
	Age uint32
	Pad1 []byte
	_io *kaitai.Stream
	_root *GrowtopiaWorld
	_parent *GrowtopiaWorld_WorldTile
}
func NewGrowtopiaWorld_ProviderExtra() *GrowtopiaWorld_ProviderExtra {
	return &GrowtopiaWorld_ProviderExtra{
	}
}

func (this GrowtopiaWorld_ProviderExtra) IO_() *kaitai.Stream {
	return this._io
}

func (this *GrowtopiaWorld_ProviderExtra) Read(io *kaitai.Stream, parent *GrowtopiaWorld_WorldTile, root *GrowtopiaWorld) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp158, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.Age = uint32(tmp158)
	if (this._parent.Fg == 10656) {
		tmp159, err := this._io.ReadBytes(int(4))
		if err != nil {
			return err
		}
		tmp159 = tmp159
		this.Pad1 = tmp159
	}
	return err
}
type GrowtopiaWorld_SafeVaultExtra struct {
	_io *kaitai.Stream
	_root *GrowtopiaWorld
	_parent *GrowtopiaWorld_WorldTile
}
func NewGrowtopiaWorld_SafeVaultExtra() *GrowtopiaWorld_SafeVaultExtra {
	return &GrowtopiaWorld_SafeVaultExtra{
	}
}

func (this GrowtopiaWorld_SafeVaultExtra) IO_() *kaitai.Stream {
	return this._io
}

func (this *GrowtopiaWorld_SafeVaultExtra) Read(io *kaitai.Stream, parent *GrowtopiaWorld_WorldTile, root *GrowtopiaWorld) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	return err
}
type GrowtopiaWorld_SeedExtra struct {
	Age uint32
	FruitCount uint8
	_io *kaitai.Stream
	_root *GrowtopiaWorld
	_parent *GrowtopiaWorld_WorldTile
}
func NewGrowtopiaWorld_SeedExtra() *GrowtopiaWorld_SeedExtra {
	return &GrowtopiaWorld_SeedExtra{
	}
}

func (this GrowtopiaWorld_SeedExtra) IO_() *kaitai.Stream {
	return this._io
}

func (this *GrowtopiaWorld_SeedExtra) Read(io *kaitai.Stream, parent *GrowtopiaWorld_WorldTile, root *GrowtopiaWorld) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp160, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.Age = uint32(tmp160)
	tmp161, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.FruitCount = tmp161
	return err
}
type GrowtopiaWorld_SewingMachineExtra struct {
	NumBoltIds uint32
	BoltIds []uint32
	_io *kaitai.Stream
	_root *GrowtopiaWorld
	_parent *GrowtopiaWorld_WorldTile
}
func NewGrowtopiaWorld_SewingMachineExtra() *GrowtopiaWorld_SewingMachineExtra {
	return &GrowtopiaWorld_SewingMachineExtra{
	}
}

func (this GrowtopiaWorld_SewingMachineExtra) IO_() *kaitai.Stream {
	return this._io
}

func (this *GrowtopiaWorld_SewingMachineExtra) Read(io *kaitai.Stream, parent *GrowtopiaWorld_WorldTile, root *GrowtopiaWorld) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp162, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.NumBoltIds = uint32(tmp162)
	for i := 0; i < int(this.NumBoltIds); i++ {
		_ = i
		tmp163, err := this._io.ReadU4le()
		if err != nil {
			return err
		}
		this.BoltIds = append(this.BoltIds, tmp163)
	}
	return err
}
type GrowtopiaWorld_ShelfExtra struct {
	TopLeftItemId uint32
	TopRightItemId uint32
	BottomLeftItemId uint32
	BottomRightItemId uint32
	_io *kaitai.Stream
	_root *GrowtopiaWorld
	_parent *GrowtopiaWorld_WorldTile
}
func NewGrowtopiaWorld_ShelfExtra() *GrowtopiaWorld_ShelfExtra {
	return &GrowtopiaWorld_ShelfExtra{
	}
}

func (this GrowtopiaWorld_ShelfExtra) IO_() *kaitai.Stream {
	return this._io
}

func (this *GrowtopiaWorld_ShelfExtra) Read(io *kaitai.Stream, parent *GrowtopiaWorld_WorldTile, root *GrowtopiaWorld) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp164, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.TopLeftItemId = uint32(tmp164)
	tmp165, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.TopRightItemId = uint32(tmp165)
	tmp166, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.BottomLeftItemId = uint32(tmp166)
	tmp167, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.BottomRightItemId = uint32(tmp167)
	return err
}
type GrowtopiaWorld_SignExtra struct {
	Label *GrowtopiaWorld_GtStr
	Pad1 []byte
	_io *kaitai.Stream
	_root *GrowtopiaWorld
	_parent *GrowtopiaWorld_WorldTile
}
func NewGrowtopiaWorld_SignExtra() *GrowtopiaWorld_SignExtra {
	return &GrowtopiaWorld_SignExtra{
	}
}

func (this GrowtopiaWorld_SignExtra) IO_() *kaitai.Stream {
	return this._io
}

func (this *GrowtopiaWorld_SignExtra) Read(io *kaitai.Stream, parent *GrowtopiaWorld_WorldTile, root *GrowtopiaWorld) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp168 := NewGrowtopiaWorld_GtStr()
	err = tmp168.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.Label = tmp168
	tmp169, err := this._io.ReadBytes(int(4))
	if err != nil {
		return err
	}
	tmp169 = tmp169
	this.Pad1 = tmp169
	return err
}
type GrowtopiaWorld_SilkWormExtra struct {
	Flags uint8
	Name *GrowtopiaWorld_GtStr
	AgeSec uint32
	Unk1 uint32
	Unk2 uint32
	CanBeFed uint8
	FoodSaturation uint32
	WaterSaturation uint32
	ColorArgb *GrowtopiaWorld_ARGB
	SickDuration uint32
	_io *kaitai.Stream
	_root *GrowtopiaWorld
	_parent *GrowtopiaWorld_WorldTile
}
func NewGrowtopiaWorld_SilkWormExtra() *GrowtopiaWorld_SilkWormExtra {
	return &GrowtopiaWorld_SilkWormExtra{
	}
}

func (this GrowtopiaWorld_SilkWormExtra) IO_() *kaitai.Stream {
	return this._io
}

func (this *GrowtopiaWorld_SilkWormExtra) Read(io *kaitai.Stream, parent *GrowtopiaWorld_WorldTile, root *GrowtopiaWorld) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp170, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.Flags = tmp170
	tmp171 := NewGrowtopiaWorld_GtStr()
	err = tmp171.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.Name = tmp171
	tmp172, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.AgeSec = uint32(tmp172)
	tmp173, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.Unk1 = uint32(tmp173)
	tmp174, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.Unk2 = uint32(tmp174)
	tmp175, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.CanBeFed = tmp175
	tmp176, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.FoodSaturation = uint32(tmp176)
	tmp177, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.WaterSaturation = uint32(tmp177)
	tmp178 := NewGrowtopiaWorld_ARGB()
	err = tmp178.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.ColorArgb = tmp178
	tmp179, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.SickDuration = uint32(tmp179)
	return err
}
type GrowtopiaWorld_SolarCollectorExtra struct {
	Unk1 []byte
	_io *kaitai.Stream
	_root *GrowtopiaWorld
	_parent *GrowtopiaWorld_WorldTile
}
func NewGrowtopiaWorld_SolarCollectorExtra() *GrowtopiaWorld_SolarCollectorExtra {
	return &GrowtopiaWorld_SolarCollectorExtra{
	}
}

func (this GrowtopiaWorld_SolarCollectorExtra) IO_() *kaitai.Stream {
	return this._io
}

func (this *GrowtopiaWorld_SolarCollectorExtra) Read(io *kaitai.Stream, parent *GrowtopiaWorld_WorldTile, root *GrowtopiaWorld) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp180, err := this._io.ReadBytes(int(5))
	if err != nil {
		return err
	}
	tmp180 = tmp180
	this.Unk1 = tmp180
	return err
}
type GrowtopiaWorld_SpiritBoardExtra struct {
	PlayerRequired uint32
	Unk1 *GrowtopiaWorld_GtStr
	Command *GrowtopiaWorld_GtStr
	NumRequiredItems uint32
	RequiredItems []uint32
	_io *kaitai.Stream
	_root *GrowtopiaWorld
	_parent *GrowtopiaWorld_WorldTile
}
func NewGrowtopiaWorld_SpiritBoardExtra() *GrowtopiaWorld_SpiritBoardExtra {
	return &GrowtopiaWorld_SpiritBoardExtra{
	}
}

func (this GrowtopiaWorld_SpiritBoardExtra) IO_() *kaitai.Stream {
	return this._io
}

func (this *GrowtopiaWorld_SpiritBoardExtra) Read(io *kaitai.Stream, parent *GrowtopiaWorld_WorldTile, root *GrowtopiaWorld) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp181, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.PlayerRequired = uint32(tmp181)
	tmp182 := NewGrowtopiaWorld_GtStr()
	err = tmp182.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.Unk1 = tmp182
	tmp183 := NewGrowtopiaWorld_GtStr()
	err = tmp183.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.Command = tmp183
	tmp184, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.NumRequiredItems = uint32(tmp184)
	for i := 0; i < int(this.NumRequiredItems); i++ {
		_ = i
		tmp185, err := this._io.ReadU4le()
		if err != nil {
			return err
		}
		this.RequiredItems = append(this.RequiredItems, tmp185)
	}
	return err
}
type GrowtopiaWorld_SpiritStorageUnitExtra struct {
	GhostJarCount uint32
	_io *kaitai.Stream
	_root *GrowtopiaWorld
	_parent *GrowtopiaWorld_WorldTile
}
func NewGrowtopiaWorld_SpiritStorageUnitExtra() *GrowtopiaWorld_SpiritStorageUnitExtra {
	return &GrowtopiaWorld_SpiritStorageUnitExtra{
	}
}

func (this GrowtopiaWorld_SpiritStorageUnitExtra) IO_() *kaitai.Stream {
	return this._io
}

func (this *GrowtopiaWorld_SpiritStorageUnitExtra) Read(io *kaitai.Stream, parent *GrowtopiaWorld_WorldTile, root *GrowtopiaWorld) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp186, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.GhostJarCount = uint32(tmp186)
	return err
}
type GrowtopiaWorld_SpotlightExtra struct {
	_io *kaitai.Stream
	_root *GrowtopiaWorld
	_parent *GrowtopiaWorld_WorldTile
}
func NewGrowtopiaWorld_SpotlightExtra() *GrowtopiaWorld_SpotlightExtra {
	return &GrowtopiaWorld_SpotlightExtra{
	}
}

func (this GrowtopiaWorld_SpotlightExtra) IO_() *kaitai.Stream {
	return this._io
}

func (this *GrowtopiaWorld_SpotlightExtra) Read(io *kaitai.Stream, parent *GrowtopiaWorld_WorldTile, root *GrowtopiaWorld) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	return err
}
type GrowtopiaWorld_SteamEngineExtra struct {
	Temperature uint32
	_io *kaitai.Stream
	_root *GrowtopiaWorld
	_parent *GrowtopiaWorld_WorldTile
}
func NewGrowtopiaWorld_SteamEngineExtra() *GrowtopiaWorld_SteamEngineExtra {
	return &GrowtopiaWorld_SteamEngineExtra{
	}
}

func (this GrowtopiaWorld_SteamEngineExtra) IO_() *kaitai.Stream {
	return this._io
}

func (this *GrowtopiaWorld_SteamEngineExtra) Read(io *kaitai.Stream, parent *GrowtopiaWorld_WorldTile, root *GrowtopiaWorld) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp187, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.Temperature = uint32(tmp187)
	return err
}
type GrowtopiaWorld_SteamOrganExtra struct {
	InstrumentType uint8
	Note uint32
	_io *kaitai.Stream
	_root *GrowtopiaWorld
	_parent *GrowtopiaWorld_WorldTile
}
func NewGrowtopiaWorld_SteamOrganExtra() *GrowtopiaWorld_SteamOrganExtra {
	return &GrowtopiaWorld_SteamOrganExtra{
	}
}

func (this GrowtopiaWorld_SteamOrganExtra) IO_() *kaitai.Stream {
	return this._io
}

func (this *GrowtopiaWorld_SteamOrganExtra) Read(io *kaitai.Stream, parent *GrowtopiaWorld_WorldTile, root *GrowtopiaWorld) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp188, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.InstrumentType = tmp188
	tmp189, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.Note = uint32(tmp189)
	return err
}
type GrowtopiaWorld_StorageBoxXtremeExtra struct {
	DataLen uint16
	Items []*GrowtopiaWorld_StorageBoxXtremeExtra_StorageItem
	_io *kaitai.Stream
	_root *GrowtopiaWorld
	_parent *GrowtopiaWorld_WorldTile
}
func NewGrowtopiaWorld_StorageBoxXtremeExtra() *GrowtopiaWorld_StorageBoxXtremeExtra {
	return &GrowtopiaWorld_StorageBoxXtremeExtra{
	}
}

func (this GrowtopiaWorld_StorageBoxXtremeExtra) IO_() *kaitai.Stream {
	return this._io
}

func (this *GrowtopiaWorld_StorageBoxXtremeExtra) Read(io *kaitai.Stream, parent *GrowtopiaWorld_WorldTile, root *GrowtopiaWorld) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp190, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.DataLen = uint16(tmp190)
	for i := 0; i < int(this.DataLen / 13); i++ {
		_ = i
		tmp191 := NewGrowtopiaWorld_StorageBoxXtremeExtra_StorageItem()
		err = tmp191.Read(this._io, this, this._root)
		if err != nil {
			return err
		}
		this.Items = append(this.Items, tmp191)
	}
	return err
}
type GrowtopiaWorld_StorageBoxXtremeExtra_StorageItem struct {
	Pad1 []byte
	ItemId uint32
	Pad2 []byte
	ItemAmt uint32
	_io *kaitai.Stream
	_root *GrowtopiaWorld
	_parent *GrowtopiaWorld_StorageBoxXtremeExtra
}
func NewGrowtopiaWorld_StorageBoxXtremeExtra_StorageItem() *GrowtopiaWorld_StorageBoxXtremeExtra_StorageItem {
	return &GrowtopiaWorld_StorageBoxXtremeExtra_StorageItem{
	}
}

func (this GrowtopiaWorld_StorageBoxXtremeExtra_StorageItem) IO_() *kaitai.Stream {
	return this._io
}

func (this *GrowtopiaWorld_StorageBoxXtremeExtra_StorageItem) Read(io *kaitai.Stream, parent *GrowtopiaWorld_StorageBoxXtremeExtra, root *GrowtopiaWorld) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp192, err := this._io.ReadBytes(int(3))
	if err != nil {
		return err
	}
	tmp192 = tmp192
	this.Pad1 = tmp192
	tmp193, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.ItemId = uint32(tmp193)
	tmp194, err := this._io.ReadBytes(int(2))
	if err != nil {
		return err
	}
	tmp194 = tmp194
	this.Pad2 = tmp194
	tmp195, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.ItemAmt = uint32(tmp195)
	return err
}
type GrowtopiaWorld_StormyCloudExtra struct {
	StingDuration uint32
	IsSolid uint32
	NonSolidDuration uint32
	_io *kaitai.Stream
	_root *GrowtopiaWorld
	_parent *GrowtopiaWorld_WorldTile
}
func NewGrowtopiaWorld_StormyCloudExtra() *GrowtopiaWorld_StormyCloudExtra {
	return &GrowtopiaWorld_StormyCloudExtra{
	}
}

func (this GrowtopiaWorld_StormyCloudExtra) IO_() *kaitai.Stream {
	return this._io
}

func (this *GrowtopiaWorld_StormyCloudExtra) Read(io *kaitai.Stream, parent *GrowtopiaWorld_WorldTile, root *GrowtopiaWorld) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp196, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.StingDuration = uint32(tmp196)
	tmp197, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.IsSolid = uint32(tmp197)
	tmp198, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.NonSolidDuration = uint32(tmp198)
	return err
}
type GrowtopiaWorld_TemporaryPlatformExtra struct {
	Unk1 uint32
	_io *kaitai.Stream
	_root *GrowtopiaWorld
	_parent *GrowtopiaWorld_WorldTile
}
func NewGrowtopiaWorld_TemporaryPlatformExtra() *GrowtopiaWorld_TemporaryPlatformExtra {
	return &GrowtopiaWorld_TemporaryPlatformExtra{
	}
}

func (this GrowtopiaWorld_TemporaryPlatformExtra) IO_() *kaitai.Stream {
	return this._io
}

func (this *GrowtopiaWorld_TemporaryPlatformExtra) Read(io *kaitai.Stream, parent *GrowtopiaWorld_WorldTile, root *GrowtopiaWorld) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp199, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.Unk1 = uint32(tmp199)
	return err
}
type GrowtopiaWorld_TesseractManipulatorExtra struct {
	GemsLeft uint32
	NextUpdateMs uint32
	ItemId uint32
	Enabled uint32
	_io *kaitai.Stream
	_root *GrowtopiaWorld
	_parent *GrowtopiaWorld_WorldTile
}
func NewGrowtopiaWorld_TesseractManipulatorExtra() *GrowtopiaWorld_TesseractManipulatorExtra {
	return &GrowtopiaWorld_TesseractManipulatorExtra{
	}
}

func (this GrowtopiaWorld_TesseractManipulatorExtra) IO_() *kaitai.Stream {
	return this._io
}

func (this *GrowtopiaWorld_TesseractManipulatorExtra) Read(io *kaitai.Stream, parent *GrowtopiaWorld_WorldTile, root *GrowtopiaWorld) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp200, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.GemsLeft = uint32(tmp200)
	tmp201, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.NextUpdateMs = uint32(tmp201)
	tmp202, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.ItemId = uint32(tmp202)
	tmp203, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.Enabled = uint32(tmp203)
	return err
}
type GrowtopiaWorld_TombRobberExtra struct {
	_io *kaitai.Stream
	_root *GrowtopiaWorld
	_parent *GrowtopiaWorld_WorldTile
}
func NewGrowtopiaWorld_TombRobberExtra() *GrowtopiaWorld_TombRobberExtra {
	return &GrowtopiaWorld_TombRobberExtra{
	}
}

func (this GrowtopiaWorld_TombRobberExtra) IO_() *kaitai.Stream {
	return this._io
}

func (this *GrowtopiaWorld_TombRobberExtra) Read(io *kaitai.Stream, parent *GrowtopiaWorld_WorldTile, root *GrowtopiaWorld) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	return err
}
type GrowtopiaWorld_TrainingPortExtra struct {
	FishLb uint32
	Status uint16
	ItemId uint32
	TotalExp uint32
	Unk1 []byte
	FishLevel uint32
	Unk2 uint32
	Unk3 []byte
	_io *kaitai.Stream
	_root *GrowtopiaWorld
	_parent *GrowtopiaWorld_WorldTile
}
func NewGrowtopiaWorld_TrainingPortExtra() *GrowtopiaWorld_TrainingPortExtra {
	return &GrowtopiaWorld_TrainingPortExtra{
	}
}

func (this GrowtopiaWorld_TrainingPortExtra) IO_() *kaitai.Stream {
	return this._io
}

func (this *GrowtopiaWorld_TrainingPortExtra) Read(io *kaitai.Stream, parent *GrowtopiaWorld_WorldTile, root *GrowtopiaWorld) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp204, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.FishLb = uint32(tmp204)
	tmp205, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.Status = uint16(tmp205)
	tmp206, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.ItemId = uint32(tmp206)
	tmp207, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.TotalExp = uint32(tmp207)
	tmp208, err := this._io.ReadBytes(int(8))
	if err != nil {
		return err
	}
	tmp208 = tmp208
	this.Unk1 = tmp208
	tmp209, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.FishLevel = uint32(tmp209)
	tmp210, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.Unk2 = uint32(tmp210)
	tmp211, err := this._io.ReadBytes(int(5))
	if err != nil {
		return err
	}
	tmp211 = tmp211
	this.Unk3 = tmp211
	return err
}
type GrowtopiaWorld_UnknownExtra struct {
	ThisIsJustToErrorOutKaitaiPls []byte
	_io *kaitai.Stream
	_root *GrowtopiaWorld
	_parent *GrowtopiaWorld_WorldTile
}
func NewGrowtopiaWorld_UnknownExtra() *GrowtopiaWorld_UnknownExtra {
	return &GrowtopiaWorld_UnknownExtra{
	}
}

func (this GrowtopiaWorld_UnknownExtra) IO_() *kaitai.Stream {
	return this._io
}

func (this *GrowtopiaWorld_UnknownExtra) Read(io *kaitai.Stream, parent *GrowtopiaWorld_WorldTile, root *GrowtopiaWorld) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp212, err := this._io.ReadBytesFull()
	if err != nil {
		return err
	}
	tmp212 = tmp212
	this.ThisIsJustToErrorOutKaitaiPls = tmp212
	return err
}

/**
 * This type is just to error out kaitai. So if you encounter any error, 
 * please either give the world name or dump the world and submit it to me
 * (81739844+badewen@users.noreply.github.com).  
 */
type GrowtopiaWorld_VendingMachineExtra struct {
	ItemId uint32
	Price int32
	_io *kaitai.Stream
	_root *GrowtopiaWorld
	_parent *GrowtopiaWorld_WorldTile
}
func NewGrowtopiaWorld_VendingMachineExtra() *GrowtopiaWorld_VendingMachineExtra {
	return &GrowtopiaWorld_VendingMachineExtra{
	}
}

func (this GrowtopiaWorld_VendingMachineExtra) IO_() *kaitai.Stream {
	return this._io
}

func (this *GrowtopiaWorld_VendingMachineExtra) Read(io *kaitai.Stream, parent *GrowtopiaWorld_WorldTile, root *GrowtopiaWorld) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp213, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.ItemId = uint32(tmp213)
	tmp214, err := this._io.ReadS4le()
	if err != nil {
		return err
	}
	this.Price = int32(tmp214)
	return err
}
type GrowtopiaWorld_VipEntranceExtra struct {
	Unk1 uint8
	OwnerUserid uint32
	NumAllowedUserids uint32
	AllowedUserids []uint32
	_io *kaitai.Stream
	_root *GrowtopiaWorld
	_parent *GrowtopiaWorld_WorldTile
}
func NewGrowtopiaWorld_VipEntranceExtra() *GrowtopiaWorld_VipEntranceExtra {
	return &GrowtopiaWorld_VipEntranceExtra{
	}
}

func (this GrowtopiaWorld_VipEntranceExtra) IO_() *kaitai.Stream {
	return this._io
}

func (this *GrowtopiaWorld_VipEntranceExtra) Read(io *kaitai.Stream, parent *GrowtopiaWorld_WorldTile, root *GrowtopiaWorld) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp215, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.Unk1 = tmp215
	tmp216, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.OwnerUserid = uint32(tmp216)
	tmp217, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.NumAllowedUserids = uint32(tmp217)
	for i := 0; i < int(this.NumAllowedUserids); i++ {
		_ = i
		tmp218, err := this._io.ReadU4le()
		if err != nil {
			return err
		}
		this.AllowedUserids = append(this.AllowedUserids, tmp218)
	}
	return err
}
type GrowtopiaWorld_WeatherMachine1Extra struct {
	Settings []byte
	_io *kaitai.Stream
	_root *GrowtopiaWorld
	_parent *GrowtopiaWorld_WorldTile
}
func NewGrowtopiaWorld_WeatherMachine1Extra() *GrowtopiaWorld_WeatherMachine1Extra {
	return &GrowtopiaWorld_WeatherMachine1Extra{
	}
}

func (this GrowtopiaWorld_WeatherMachine1Extra) IO_() *kaitai.Stream {
	return this._io
}

func (this *GrowtopiaWorld_WeatherMachine1Extra) Read(io *kaitai.Stream, parent *GrowtopiaWorld_WorldTile, root *GrowtopiaWorld) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp219, err := this._io.ReadBytes(int(4))
	if err != nil {
		return err
	}
	tmp219 = tmp219
	this.Settings = tmp219
	return err
}
type GrowtopiaWorld_WeatherMachine2Extra struct {
	ItemId uint32
	Gravity uint32
	Flag uint8
	_io *kaitai.Stream
	_root *GrowtopiaWorld
	_parent *GrowtopiaWorld_WorldTile
}
func NewGrowtopiaWorld_WeatherMachine2Extra() *GrowtopiaWorld_WeatherMachine2Extra {
	return &GrowtopiaWorld_WeatherMachine2Extra{
	}
}

func (this GrowtopiaWorld_WeatherMachine2Extra) IO_() *kaitai.Stream {
	return this._io
}

func (this *GrowtopiaWorld_WeatherMachine2Extra) Read(io *kaitai.Stream, parent *GrowtopiaWorld_WorldTile, root *GrowtopiaWorld) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp220, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.ItemId = uint32(tmp220)
	tmp221, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.Gravity = uint32(tmp221)
	tmp222, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.Flag = tmp222
	return err
}
type GrowtopiaWorld_WorldObject struct {
	ItemId uint16
	X float32
	Y float32
	Amount uint8
	Flag uint8
	Uid uint32
	_io *kaitai.Stream
	_root *GrowtopiaWorld
	_parent *GrowtopiaWorld
}
func NewGrowtopiaWorld_WorldObject() *GrowtopiaWorld_WorldObject {
	return &GrowtopiaWorld_WorldObject{
	}
}

func (this GrowtopiaWorld_WorldObject) IO_() *kaitai.Stream {
	return this._io
}

func (this *GrowtopiaWorld_WorldObject) Read(io *kaitai.Stream, parent *GrowtopiaWorld, root *GrowtopiaWorld) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp223, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.ItemId = uint16(tmp223)
	tmp224, err := this._io.ReadF4le()
	if err != nil {
		return err
	}
	this.X = float32(tmp224)
	tmp225, err := this._io.ReadF4le()
	if err != nil {
		return err
	}
	this.Y = float32(tmp225)
	tmp226, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.Amount = tmp226
	tmp227, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.Flag = tmp227
	tmp228, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.Uid = uint32(tmp228)
	return err
}
type GrowtopiaWorld_WorldTile struct {
	Fg uint16
	Bg uint16
	InvalidTileFgBgKaitaiCrasher []byte
	ParentBlockIndex uint16
	Flag uint16
	ParentLock uint16
	ExtraDataType uint8
	TileExtra kaitai.Struct
	CborData *GrowtopiaWorld_CborData
	_io *kaitai.Stream
	_root *GrowtopiaWorld
	_parent *GrowtopiaWorld
}
func NewGrowtopiaWorld_WorldTile() *GrowtopiaWorld_WorldTile {
	return &GrowtopiaWorld_WorldTile{
	}
}

func (this GrowtopiaWorld_WorldTile) IO_() *kaitai.Stream {
	return this._io
}

func (this *GrowtopiaWorld_WorldTile) Read(io *kaitai.Stream, parent *GrowtopiaWorld, root *GrowtopiaWorld) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp229, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.Fg = uint16(tmp229)
	tmp230, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.Bg = uint16(tmp230)
	if ( ((this.Fg > 25000) || (this.Bg > 25000)) ) {
		tmp231, err := this._io.ReadBytesFull()
		if err != nil {
			return err
		}
		tmp231 = tmp231
		this.InvalidTileFgBgKaitaiCrasher = tmp231
	}
	tmp232, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.ParentBlockIndex = uint16(tmp232)
	tmp233, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.Flag = uint16(tmp233)
	if (this.Flag & 2 == 2) {
		tmp234, err := this._io.ReadU2le()
		if err != nil {
			return err
		}
		this.ParentLock = uint16(tmp234)
	}
	if (this.Flag & 1 == 1) {
		tmp235, err := this._io.ReadU1()
		if err != nil {
			return err
		}
		this.ExtraDataType = tmp235
	}
	if (this.Flag & 1 == 1) {
		switch (this.ExtraDataType) {
		case 1:
			tmp236 := NewGrowtopiaWorld_DoorExtra()
			err = tmp236.Read(this._io, this, this._root)
			if err != nil {
				return err
			}
			this.TileExtra = tmp236
		case 10:
			tmp237 := NewGrowtopiaWorld_AchievementBlockExtra()
			err = tmp237.Read(this._io, this, this._root)
			if err != nil {
				return err
			}
			this.TileExtra = tmp237
		case 11:
			tmp238 := NewGrowtopiaWorld_HeartMonitorExtra()
			err = tmp238.Read(this._io, this, this._root)
			if err != nil {
				return err
			}
			this.TileExtra = tmp238
		case 14:
			tmp239 := NewGrowtopiaWorld_MannequinExtra()
			err = tmp239.Read(this._io, this, this._root)
			if err != nil {
				return err
			}
			this.TileExtra = tmp239
		case 15:
			tmp240 := NewGrowtopiaWorld_MagicEggExtra()
			err = tmp240.Read(this._io, this, this._root)
			if err != nil {
				return err
			}
			this.TileExtra = tmp240
		case 16:
			tmp241 := NewGrowtopiaWorld_GameGraveExtra()
			err = tmp241.Read(this._io, this, this._root)
			if err != nil {
				return err
			}
			this.TileExtra = tmp241
		case 17:
			tmp242 := NewGrowtopiaWorld_GameGeneratorExtra()
			err = tmp242.Read(this._io, this, this._root)
			if err != nil {
				return err
			}
			this.TileExtra = tmp242
		case 18:
			tmp243 := NewGrowtopiaWorld_XenoniteExtra()
			err = tmp243.Read(this._io, this, this._root)
			if err != nil {
				return err
			}
			this.TileExtra = tmp243
		case 19:
			tmp244 := NewGrowtopiaWorld_PhoneBoothExtra()
			err = tmp244.Read(this._io, this, this._root)
			if err != nil {
				return err
			}
			this.TileExtra = tmp244
		case 2:
			tmp245 := NewGrowtopiaWorld_SignExtra()
			err = tmp245.Read(this._io, this, this._root)
			if err != nil {
				return err
			}
			this.TileExtra = tmp245
		case 20:
			tmp246 := NewGrowtopiaWorld_CrystalExtra()
			err = tmp246.Read(this._io, this, this._root)
			if err != nil {
				return err
			}
			this.TileExtra = tmp246
		case 21:
			tmp247 := NewGrowtopiaWorld_CrimeInProgressExtra()
			err = tmp247.Read(this._io, this, this._root)
			if err != nil {
				return err
			}
			this.TileExtra = tmp247
		case 22:
			tmp248 := NewGrowtopiaWorld_SpotlightExtra()
			err = tmp248.Read(this._io, this, this._root)
			if err != nil {
				return err
			}
			this.TileExtra = tmp248
		case 23:
			tmp249 := NewGrowtopiaWorld_DisplayBlockExtra()
			err = tmp249.Read(this._io, this, this._root)
			if err != nil {
				return err
			}
			this.TileExtra = tmp249
		case 24:
			tmp250 := NewGrowtopiaWorld_VendingMachineExtra()
			err = tmp250.Read(this._io, this, this._root)
			if err != nil {
				return err
			}
			this.TileExtra = tmp250
		case 25:
			tmp251 := NewGrowtopiaWorld_FishTankPortExtra()
			err = tmp251.Read(this._io, this, this._root)
			if err != nil {
				return err
			}
			this.TileExtra = tmp251
		case 26:
			tmp252 := NewGrowtopiaWorld_SolarCollectorExtra()
			err = tmp252.Read(this._io, this, this._root)
			if err != nil {
				return err
			}
			this.TileExtra = tmp252
		case 27:
			tmp253 := NewGrowtopiaWorld_ForgeExtra()
			err = tmp253.Read(this._io, this, this._root)
			if err != nil {
				return err
			}
			this.TileExtra = tmp253
		case 28:
			tmp254 := NewGrowtopiaWorld_GivingTreeExtra()
			err = tmp254.Read(this._io, this, this._root)
			if err != nil {
				return err
			}
			this.TileExtra = tmp254
		case 3:
			tmp255 := NewGrowtopiaWorld_LockExtra()
			err = tmp255.Read(this._io, this, this._root)
			if err != nil {
				return err
			}
			this.TileExtra = tmp255
		case 30:
			tmp256 := NewGrowtopiaWorld_SteamOrganExtra()
			err = tmp256.Read(this._io, this, this._root)
			if err != nil {
				return err
			}
			this.TileExtra = tmp256
		case 31:
			tmp257 := NewGrowtopiaWorld_SilkWormExtra()
			err = tmp257.Read(this._io, this, this._root)
			if err != nil {
				return err
			}
			this.TileExtra = tmp257
		case 32:
			tmp258 := NewGrowtopiaWorld_SewingMachineExtra()
			err = tmp258.Read(this._io, this, this._root)
			if err != nil {
				return err
			}
			this.TileExtra = tmp258
		case 33:
			tmp259 := NewGrowtopiaWorld_CountryFlagExtra()
			err = tmp259.Read(this._io, this, this._root)
			if err != nil {
				return err
			}
			this.TileExtra = tmp259
		case 34:
			tmp260 := NewGrowtopiaWorld_LobsterTrapExtra()
			err = tmp260.Read(this._io, this, this._root)
			if err != nil {
				return err
			}
			this.TileExtra = tmp260
		case 35:
			tmp261 := NewGrowtopiaWorld_PaintingEaselExtra()
			err = tmp261.Read(this._io, this, this._root)
			if err != nil {
				return err
			}
			this.TileExtra = tmp261
		case 36:
			tmp262 := NewGrowtopiaWorld_PetBattleCageExtra()
			err = tmp262.Read(this._io, this, this._root)
			if err != nil {
				return err
			}
			this.TileExtra = tmp262
		case 37:
			tmp263 := NewGrowtopiaWorld_PetTrainerExtra()
			err = tmp263.Read(this._io, this, this._root)
			if err != nil {
				return err
			}
			this.TileExtra = tmp263
		case 38:
			tmp264 := NewGrowtopiaWorld_SteamEngineExtra()
			err = tmp264.Read(this._io, this, this._root)
			if err != nil {
				return err
			}
			this.TileExtra = tmp264
		case 39:
			tmp265 := NewGrowtopiaWorld_LockBotExtra()
			err = tmp265.Read(this._io, this, this._root)
			if err != nil {
				return err
			}
			this.TileExtra = tmp265
		case 4:
			tmp266 := NewGrowtopiaWorld_SeedExtra()
			err = tmp266.Read(this._io, this, this._root)
			if err != nil {
				return err
			}
			this.TileExtra = tmp266
		case 40:
			tmp267 := NewGrowtopiaWorld_WeatherMachine1Extra()
			err = tmp267.Read(this._io, this, this._root)
			if err != nil {
				return err
			}
			this.TileExtra = tmp267
		case 41:
			tmp268 := NewGrowtopiaWorld_SpiritStorageUnitExtra()
			err = tmp268.Read(this._io, this, this._root)
			if err != nil {
				return err
			}
			this.TileExtra = tmp268
		case 42:
			tmp269 := NewGrowtopiaWorld_DataBedrockExtra()
			err = tmp269.Read(this._io, this, this._root)
			if err != nil {
				return err
			}
			this.TileExtra = tmp269
		case 43:
			tmp270 := NewGrowtopiaWorld_ShelfExtra()
			err = tmp270.Read(this._io, this, this._root)
			if err != nil {
				return err
			}
			this.TileExtra = tmp270
		case 44:
			tmp271 := NewGrowtopiaWorld_VipEntranceExtra()
			err = tmp271.Read(this._io, this, this._root)
			if err != nil {
				return err
			}
			this.TileExtra = tmp271
		case 45:
			tmp272 := NewGrowtopiaWorld_ChallengeTimerExtra()
			err = tmp272.Read(this._io, this, this._root)
			if err != nil {
				return err
			}
			this.TileExtra = tmp272
		case 47:
			tmp273 := NewGrowtopiaWorld_FishWallMountExtra()
			err = tmp273.Read(this._io, this, this._root)
			if err != nil {
				return err
			}
			this.TileExtra = tmp273
		case 48:
			tmp274 := NewGrowtopiaWorld_PortraitExtra()
			err = tmp274.Read(this._io, this, this._root)
			if err != nil {
				return err
			}
			this.TileExtra = tmp274
		case 49:
			tmp275 := NewGrowtopiaWorld_WeatherMachine2Extra()
			err = tmp275.Read(this._io, this, this._root)
			if err != nil {
				return err
			}
			this.TileExtra = tmp275
		case 50:
			tmp276 := NewGrowtopiaWorld_FossilPrepStationExtra()
			err = tmp276.Read(this._io, this, this._root)
			if err != nil {
				return err
			}
			this.TileExtra = tmp276
		case 51:
			tmp277 := NewGrowtopiaWorld_DnaExtractorExtra()
			err = tmp277.Read(this._io, this, this._root)
			if err != nil {
				return err
			}
			this.TileExtra = tmp277
		case 52:
			tmp278 := NewGrowtopiaWorld_HowlerExtra()
			err = tmp278.Read(this._io, this, this._root)
			if err != nil {
				return err
			}
			this.TileExtra = tmp278
		case 53:
			tmp279 := NewGrowtopiaWorld_ChemsynthTankExtra()
			err = tmp279.Read(this._io, this, this._root)
			if err != nil {
				return err
			}
			this.TileExtra = tmp279
		case 54:
			tmp280 := NewGrowtopiaWorld_StorageBoxXtremeExtra()
			err = tmp280.Read(this._io, this, this._root)
			if err != nil {
				return err
			}
			this.TileExtra = tmp280
		case 55:
			tmp281 := NewGrowtopiaWorld_CookingOvenExtra()
			err = tmp281.Read(this._io, this, this._root)
			if err != nil {
				return err
			}
			this.TileExtra = tmp281
		case 56:
			tmp282 := NewGrowtopiaWorld_AudioRackExtra()
			err = tmp282.Read(this._io, this, this._root)
			if err != nil {
				return err
			}
			this.TileExtra = tmp282
		case 57:
			tmp283 := NewGrowtopiaWorld_GeigerChargerExtra()
			err = tmp283.Read(this._io, this, this._root)
			if err != nil {
				return err
			}
			this.TileExtra = tmp283
		case 58:
			tmp284 := NewGrowtopiaWorld_AdventureBeginsExtra()
			err = tmp284.Read(this._io, this, this._root)
			if err != nil {
				return err
			}
			this.TileExtra = tmp284
		case 59:
			tmp285 := NewGrowtopiaWorld_TombRobberExtra()
			err = tmp285.Read(this._io, this, this._root)
			if err != nil {
				return err
			}
			this.TileExtra = tmp285
		case 60:
			tmp286 := NewGrowtopiaWorld_BalloonOMaticExtra()
			err = tmp286.Read(this._io, this, this._root)
			if err != nil {
				return err
			}
			this.TileExtra = tmp286
		case 61:
			tmp287 := NewGrowtopiaWorld_TrainingPortExtra()
			err = tmp287.Read(this._io, this, this._root)
			if err != nil {
				return err
			}
			this.TileExtra = tmp287
		case 62:
			tmp288 := NewGrowtopiaWorld_ItemSuckerExtra()
			err = tmp288.Read(this._io, this, this._root)
			if err != nil {
				return err
			}
			this.TileExtra = tmp288
		case 63:
			tmp289 := NewGrowtopiaWorld_CybotExtra()
			err = tmp289.Read(this._io, this, this._root)
			if err != nil {
				return err
			}
			this.TileExtra = tmp289
		case 65:
			tmp290 := NewGrowtopiaWorld_GuildExtra()
			err = tmp290.Read(this._io, this, this._root)
			if err != nil {
				return err
			}
			this.TileExtra = tmp290
		case 66:
			tmp291 := NewGrowtopiaWorld_GrowscanExtra()
			err = tmp291.Read(this._io, this, this._root)
			if err != nil {
				return err
			}
			this.TileExtra = tmp291
		case 67:
			tmp292 := NewGrowtopiaWorld_ContainmentFieldPowerNodeExtra()
			err = tmp292.Read(this._io, this, this._root)
			if err != nil {
				return err
			}
			this.TileExtra = tmp292
		case 68:
			tmp293 := NewGrowtopiaWorld_SpiritBoardExtra()
			err = tmp293.Read(this._io, this, this._root)
			if err != nil {
				return err
			}
			this.TileExtra = tmp293
		case 69:
			tmp294 := NewGrowtopiaWorld_TesseractManipulatorExtra()
			err = tmp294.Read(this._io, this, this._root)
			if err != nil {
				return err
			}
			this.TileExtra = tmp294
		case 72:
			tmp295 := NewGrowtopiaWorld_StormyCloudExtra()
			err = tmp295.Read(this._io, this, this._root)
			if err != nil {
				return err
			}
			this.TileExtra = tmp295
		case 73:
			tmp296 := NewGrowtopiaWorld_TemporaryPlatformExtra()
			err = tmp296.Read(this._io, this, this._root)
			if err != nil {
				return err
			}
			this.TileExtra = tmp296
		case 74:
			tmp297 := NewGrowtopiaWorld_SafeVaultExtra()
			err = tmp297.Read(this._io, this, this._root)
			if err != nil {
				return err
			}
			this.TileExtra = tmp297
		case 75:
			tmp298 := NewGrowtopiaWorld_AngelicCountingCloudExtra()
			err = tmp298.Read(this._io, this, this._root)
			if err != nil {
				return err
			}
			this.TileExtra = tmp298
		case 77:
			tmp299 := NewGrowtopiaWorld_InfinityWeatherMachineExtra()
			err = tmp299.Read(this._io, this, this._root)
			if err != nil {
				return err
			}
			this.TileExtra = tmp299
		case 79:
			tmp300 := NewGrowtopiaWorld_PineappleGuzzlerExtra()
			err = tmp300.Read(this._io, this, this._root)
			if err != nil {
				return err
			}
			this.TileExtra = tmp300
		case 8:
			tmp301 := NewGrowtopiaWorld_DiceExtra()
			err = tmp301.Read(this._io, this, this._root)
			if err != nil {
				return err
			}
			this.TileExtra = tmp301
		case 80:
			tmp302 := NewGrowtopiaWorld_KrakensGalaticBlockExtra()
			err = tmp302.Read(this._io, this, this._root)
			if err != nil {
				return err
			}
			this.TileExtra = tmp302
		case 81:
			tmp303 := NewGrowtopiaWorld_FriendsEntranceExtra()
			err = tmp303.Read(this._io, this, this._root)
			if err != nil {
				return err
			}
			this.TileExtra = tmp303
		case 9:
			tmp304 := NewGrowtopiaWorld_ProviderExtra()
			err = tmp304.Read(this._io, this, this._root)
			if err != nil {
				return err
			}
			this.TileExtra = tmp304
		default:
			tmp305 := NewGrowtopiaWorld_UnknownExtra()
			err = tmp305.Read(this._io, this, this._root)
			if err != nil {
				return err
			}
			this.TileExtra = tmp305
		}
	}
	if ( (( ((this.Flag & 1 == 1) && (this.ExtraDataType == 36)) ) || (this.Fg == 15546) || (this.Fg == 14666) || (this.Fg == 14962) || (this.Fg == 14662)) ) {
		tmp306 := NewGrowtopiaWorld_CborData()
		err = tmp306.Read(this._io, this, this._root)
		if err != nil {
			return err
		}
		this.CborData = tmp306
	}
	return err
}

/**
 * This type is just to error out kaitai. If this is 
 * encountered, then maybe there was a parsing error.
 * Please report :)
 */
type GrowtopiaWorld_XenoniteExtra struct {
	Unk1 []byte
	_io *kaitai.Stream
	_root *GrowtopiaWorld
	_parent *GrowtopiaWorld_WorldTile
}
func NewGrowtopiaWorld_XenoniteExtra() *GrowtopiaWorld_XenoniteExtra {
	return &GrowtopiaWorld_XenoniteExtra{
	}
}

func (this GrowtopiaWorld_XenoniteExtra) IO_() *kaitai.Stream {
	return this._io
}

func (this *GrowtopiaWorld_XenoniteExtra) Read(io *kaitai.Stream, parent *GrowtopiaWorld_WorldTile, root *GrowtopiaWorld) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp307, err := this._io.ReadBytes(int(5))
	if err != nil {
		return err
	}
	tmp307 = tmp307
	this.Unk1 = tmp307
	return err
}
